version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - pip install sagemaker boto3 torch scikit-learn pandas
  build:
    commands:
      - echo "Starting SageMaker Training Job..."
      - python src/train_estimator.py
artifacts:
  files:
    - '**/*'
